ARG IMAGE_NAME
FROM ${IMAGE_NAME}:{{ ctx.drivers.version }}-{{ ctx.shortName }}-jetpack-{{ ctx.jetpackVersion }}-devel as builder

{% if ctx.drivers.version == "32.4.3" -%}
WORKDIR /usr/local/cuda-10.2/samples
{% else %}
WORKDIR /usr/local/cuda-10.0/samples
{% endif %}
RUN make -j4

ARG IMAGE_NAME
FROM ${IMAGE_NAME}:{{ ctx.drivers.version }}-{{ ctx.shortName }}-jetpack-{{ ctx.jetpackVersion }}-runtime as base

# Prereqs

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    freeglut3 \
    libegl1 \
    libx11-dev \
    libgles2-mesa \
    libgl1-mesa-glx \
    libglu1-mesa \
    libgomp1 \
    libxi-dev \
    libxmu-dev \
    openmpi-bin \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

FROM base
RUN mkdir samples
{% if ctx.drivers.version == "32.4.3" -%}
COPY --from=builder /usr/local/cuda-10.2/samples/ /samples
{% else %}
COPY --from=builder /usr/local/cuda-10.0/samples/ /samples
{% endif %}

WORKDIR /samples/bin/aarch64/linux/release/
