#!make

# Default squash as our base images need to be small unless overridden
DOCKER_BUILD_ARGS ?= --squash

NV_LOGIN_TYPE ?= devzone

.PHONY: all

{% for driver_version, value in ctx.items() %}
{%- for device_name, driver_details in ctx[driver_version].items() %}
{%- if loop.first %}{{ driver_version }}-jetpack-{{ driver_details.jetpackVersion }}: {% endif %}{{ driver_version }}-{{ device_name }}-jetpack-{{ driver_details.jetpackVersion }}{{ ", " if not loop.last else "" }}{%- endfor %}
{% endfor %}

{% for driver_version, value in ctx.items() %}
{% for device_name, driver_details in ctx[driver_version].items() %}
{{ driver_version }}-{{ device_name }}-jetpack-{{ driver_details.jetpackVersion }}: {{ driver_version }}-{{ device_name }}-jetpack-{{ driver_details.jetpackVersion }}-base, {{ driver_version }}-{{ device_name }}-jetpack-{{ driver_details.jetpackVersion }}-runtime, {{ driver_version }}-{{ device_name }}-jetpack-{{ driver_details.jetpackVersion }}-devel {% endfor %}
{% endfor %}

%-from-deps-folder:
	$(DOCKER) build \
					--build-arg VERSION_ID="$(BIONIC_VERSION_ID)" \
					-t $(REPO):$*-deps \
					-f $(CURDIR)/dependencies.Dockerfile \
					$(SDKM_DOWNLOADS)

{% for driver_version, value in ctx.items() %}
{% for device_name, driver_details in ctx[driver_version].items() %}
{{ driver_version }}-{{ device_name }}-jetpack-{{ driver_details.jetpackVersion }}-deps:
	DEVICE_ID={{ driver_details.deviceId }} DEVICE_OPTION=--target NV_USER=$(NV_USER) NV_LOGIN_TYPE=$(NV_LOGIN_TYPE) PRODUCT=Jetson JETPACK_VERSION="{{ driver_details.sdkmanagerJetPackVersion }}" TARGET_OS=Linux ACCEPT_SDK_LICENCE=accept /bin/bash -c ./download-jetpack.sh

	$(DOCKER) build \
					--build-arg VERSION_ID="$(BIONIC_VERSION_ID)" \
					-t $(REPO):$@ \
					-f $(CURDIR)/dependencies.Dockerfile \
					/tmp/{{ driver_details.sdkmanagerJetPackVersion }}/{{ driver_details.deviceId }}
{% endfor %}
{% endfor %}

{% for driver_version, value in ctx.items() %}
{% for device_name, driver_details in ctx[driver_version].items() %}
{{ driver_version }}-{{ device_name }}-jetpack-{{ driver_details.jetpackVersion }}-base:
	$(DOCKER) build $(DOCKER_BUILD_ARGS) \
					--build-arg IMAGE_NAME=$(IMAGE_NAME) \
					--build-arg DEPENDENCIES_IMAGE=$(REPO):{{ driver_version }}-jax-jetpack-{{ driver_details.jetpackVersion }}-deps \
					-t $(REPO):$@ \
					-f {{ driver_details.jetpackVersion }}/{{ device_name }}/base/Dockerfile \
					.

{{ driver_version }}-{{ device_name }}-jetpack-{{ driver_details.jetpackVersion }}-runtime: {{ driver_version }}-{{ device_name }}-jetpack-{{ driver_details.jetpackVersion }}-base
	$(DOCKER) build $(DOCKER_BUILD_ARGS) \
					--build-arg IMAGE_NAME=$(IMAGE_NAME) \
					--build-arg DEPENDENCIES_IMAGE=$(REPO):{{ driver_version }}-jax-jetpack-{{ driver_details.jetpackVersion }}-deps \
					-t $(REPO):$@ \
					-f {{ driver_details.jetpackVersion }}/{{ device_name }}/runtime/Dockerfile \
					.

{{ driver_version }}-{{ device_name }}-jetpack-{{ driver_details.jetpackVersion }}-devel: {{ driver_version }}-{{ device_name }}-jetpack-{{ driver_details.jetpackVersion }}-runtime
	$(DOCKER) build $(DOCKER_BUILD_ARGS) \
					--build-arg IMAGE_NAME=$(IMAGE_NAME) \
					--build-arg DEPENDENCIES_IMAGE=$(REPO):{{ driver_version }}-jax-jetpack-{{ driver_details.jetpackVersion }}-deps \
					-t $(REPO):$@ \
					-f {{ driver_details.jetpackVersion }}/{{ device_name }}/devel/Dockerfile \
					.
{% endfor %}
{% endfor %}
