ARG VERSION_ID
ARG DEPENDENCIES_IMAGE
ARG IMAGE_NAME
FROM ${DEPENDENCIES_IMAGE} as dependencies

ARG VERSION_ID
# using a smaller image doesn't save us any space as the layers are used by the other images.
FROM ubuntu:${VERSION_ID} as qemu

# install qemu for the support of building containers on host
RUN apt-get update && apt-get install -y --no-install-recommends qemu-user-static && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# start of the real image base
ARG VERSION_ID
FROM arm64v8/ubuntu:${VERSION_ID}

LABEL maintainer "Ian Davis"

# TODO: Set up conditional QEMU support for those that haven't configured binfmt.service.
# This is small overhead (3-4 MiB) and helps people fall into the pit of success.
COPY --from=qemu /usr/bin/qemu-aarch64-static /usr/bin/qemu-aarch64-static

RUN apt-get update && apt-get install -y --no-install-recommends \
    bzip2 \
    lbzip2 \
{%- if ctx.drivers.version == "32.3.1" %}
    ca-certificates \
    gnupg \
{%- elif ctx.drivers.version == "32.4.3" or ctx.drivers.version == "32.4.4" %}
    ca-certificates \
    gnupg \
{%- endif %}
    sudo

# Copy the driver pack and verify
ARG DEPENDENCIES_IMAGE
COPY --from=dependencies /data/{{ ctx.drivers.fileName }} {{ ctx.drivers.fileName }}
{%- if ctx.drivers.checksumType == "sha1" %}
RUN echo "{{ ctx.drivers.checksum }} *./{{ ctx.drivers.fileName }}" | sha1sum -c --strict -
{%- elif ctx.drivers.checksumType == "md5" %}
RUN echo "{{ ctx.drivers.checksum }} *./{{ ctx.drivers.fileName }}" | md5sum -c -
{%- endif %}
RUN tar -xpj --overwrite -f ./{{ ctx.drivers.fileName }}

{%- if ctx.drivers.version == "32.4.3" or ctx.drivers.version == "32.4.4" %}
RUN sed -i '/.*tar -I lbzip2 -xpmf \"${LDK_NV_TEGRA_DIR}\/config\.tbz2\".*/c\tar -I lbzip2 -xpm --overwrite -f \"${LDK_NV_TEGRA_DIR}\/config.tbz2\"' ./Linux_for_Tegra/apply_binaries.sh
{%- else %}
{%- if ctx.jetpackVersion != "4.2" %}
RUN sed -i '/.*tar -I lbzip2 -xpmf ${LDK_NV_TEGRA_DIR}\/config\.tbz2.*/c\tar -I lbzip2 -xpm --overwrite -f ${LDK_NV_TEGRA_DIR}\/config.tbz2' ./Linux_for_Tegra/apply_binaries.sh
{%- endif %}
{%- endif %}

{%- if ctx.drivers.version == "32.3.1" and ctx.target_overlay == False %}
# pre-req for Linux_for_Tegra/nv_tegra/nv-apply-debs.sh as it tries to chroot
COPY --from=qemu /usr/bin/qemu-aarch64-static /Linux_for_Tegra/nv_tegra/qemu-aarch64-static
RUN sed -i '/.*LC_ALL=C chroot . mount -t proc none \/proc.*/c\#LC_ALL=C chroot . mount -t proc none \/proc' ./Linux_for_Tegra/nv_tegra/nv-apply-debs.sh
RUN sed -i '/.*LC_ALL=C APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 chroot . apt-key add \"\/etc\/apt\/jetson-ota-public.key\".*/c\apt-key add \"\/etc\/apt\/jetson-ota-public.key\"' ./Linux_for_Tegra/nv_tegra/nv-apply-debs.sh
RUN sed -i '/.*umount ${L4T_ROOTFS_DIR}\/proc.*/c\#umount ${L4T_ROOTFS_DIR}\/proc' ./Linux_for_Tegra/nv_tegra/nv-apply-debs.sh
RUN sed -i '/.*	LC_ALL=C chroot . dpkg -i --path-include=\"\/usr\/share\/doc\/\*\" \"${pre_deb_list\[\@\]}\".*/c\	apt install -y --no-install-recommends \"${pre_deb_list[@]}\"' ./Linux_for_Tegra/nv_tegra/nv-apply-debs.sh
RUN sed -i '/.*LC_ALL=C chroot . dpkg -i --path-include=\"\/usr\/share\/doc\/\*\" \"${deb_list\[\@\]}\".*/c\apt install -y --no-install-recommends \"${deb_list[@]}\"' ./Linux_for_Tegra/nv_tegra/nv-apply-debs.sh
RUN sed -i '/.*rm -f "${L4T_ROOTFS_DIR}\/usr\/bin\/qemu-aarch64-static\".*/c\#rm -f "${L4T_ROOTFS_DIR}\/usr\/bin\/qemu-aarch64-static\"' ./Linux_for_Tegra/nv_tegra/nv-apply-debs.sh
{% endif %}
{%- if ctx.drivers.version == "32.4.3" and ctx.target_overlay == False %}
# pre-req for Linux_for_Tegra/nv_tegra/nv-apply-debs.sh as it tries to chroot
COPY --from=qemu /usr/bin/qemu-aarch64-static /Linux_for_Tegra/nv_tegra/qemu-aarch64-static
RUN sed -i '/.*	LC_ALL=C chroot . dpkg -i --path-include=\"\/usr\/share\/doc\/\*\" \"${pre_deb_list\[\@\]}\".*/c\	apt install -y --no-install-recommends \"${pre_deb_list[@]}\"' ./Linux_for_Tegra/nv_tegra/nv-apply-debs.sh
RUN sed -i '/.*LC_ALL=C chroot . dpkg -i --path-include=\"\/usr\/share\/doc\/\*\" \"${deb_list\[\@\]}\".*/c\apt install -y --no-install-recommends \"${deb_list[@]}\"' ./Linux_for_Tegra/nv_tegra/nv-apply-debs.sh
RUN sed -i '/.*rm -f "${L4T_ROOTFS_DIR}\/usr\/bin\/qemu-aarch64-static\".*/c\#rm -f "${L4T_ROOTFS_DIR}\/usr\/bin\/qemu-aarch64-static\"' ./Linux_for_Tegra/nv_tegra/nv-apply-debs.sh
{% endif %}
{%- if ctx.drivers.version == "32.4.4" and ctx.target_overlay == False %}
# pre-req for Linux_for_Tegra/nv_tegra/nv-apply-debs.sh as it tries to chroot
COPY --from=qemu /usr/bin/qemu-aarch64-static /Linux_for_Tegra/nv_tegra/qemu-aarch64-static
RUN sed -i '/.*	LC_ALL=C chroot . dpkg -i --path-include=\"\/usr\/share\/doc\/\*\" \"${pre_deb_list\[\@\]}\".*/c\	apt install -y --no-install-recommends \"${pre_deb_list[@]}\"' ./Linux_for_Tegra/nv_tegra/nv-apply-debs.sh
RUN sed -i '/.*LC_ALL=C chroot . dpkg -i --path-include=\"\/usr\/share\/doc\/\*\" \"${deb_list\[\@\]}\".*/c\apt install -y --no-install-recommends \"${deb_list[@]}\"' ./Linux_for_Tegra/nv_tegra/nv-apply-debs.sh
RUN sed -i '/.*rm -f "${L4T_ROOTFS_DIR}\/usr\/bin\/qemu-aarch64-static\".*/c\#rm -f "${L4T_ROOTFS_DIR}\/usr\/bin\/qemu-aarch64-static\"' ./Linux_for_Tegra/nv_tegra/nv-apply-debs.sh
{% endif %}

{%- if ctx.drivers.version == "32.3.1" or ctx.drivers.version == "32.4.3" or ctx.drivers.version == "32.4.4" %}
# In {{ ctx.drivers.version }}, this will use deb packages instead of the archive overlay
{%- endif %}
{%- if ctx.drivers.version == "32.3.1" and ctx.target_overlay == True %}
RUN ./Linux_for_Tegra/apply_binaries.sh -r / --target-overlay
{%- elif ctx.drivers.version == "32.4.3" and ctx.target_overlay == True %}
RUN ./Linux_for_Tegra/apply_binaries.sh -r / --target-overlay
{%- elif ctx.drivers.version == "32.4.4" and ctx.target_overlay == True %}
RUN ./Linux_for_Tegra/apply_binaries.sh -r / --target-overlay
{% else %}
RUN ./Linux_for_Tegra/apply_binaries.sh -r /
{% endif %}

{%- if ctx.drivers.version == "32.3.1" and ctx.target_overlay == False %}
# Patch OTA apt source
RUN sed -i "s/<SOC>/t{{ ctx.SOC }}/g" "/etc/apt/sources.list.d/nvidia-l4t-apt-source.list"
{%- endif %}
{%- if ctx.drivers.version == "32.4.3" and ctx.target_overlay == False %}
# Patch OTA apt source
RUN sed -i "s/<SOC>/t{{ ctx.SOC }}/g" "/etc/apt/sources.list.d/nvidia-l4t-apt-source.list"
{%- endif %}
{%- if ctx.drivers.version == "32.4.4" and ctx.target_overlay == False %}
# Patch OTA apt source
RUN sed -i "s/<SOC>/t{{ ctx.SOC }}/g" "/etc/apt/sources.list.d/nvidia-l4t-apt-source.list"
{%- endif %}

# Cleanup so --squash will be effective
RUN rm -rf ./Linux_for_Tegra && \
    rm ./{{ ctx.drivers.fileName }} \
    && \
    apt-get purge --autoremove -y bzip2 lbzip2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra-egl:${LD_LIBRARY_PATH}

RUN ln -s /usr/lib/aarch64-linux-gnu/tegra/libnvidia-ptxjitcompiler.so.{{ ctx.drivers.version }} /usr/lib/aarch64-linux-gnu/tegra/libnvidia-ptxjitcompiler.so
RUN ln -s /usr/lib/aarch64-linux-gnu/tegra/libnvidia-ptxjitcompiler.so.{{ ctx.drivers.version }} /usr/lib/aarch64-linux-gnu/tegra/libnvidia-ptxjitcompiler.so.1
RUN ln -sf /usr/lib/aarch64-linux-gnu/tegra/libGL.so /usr/lib/aarch64-linux-gnu/libGL.so
RUN ln -s /usr/lib/aarch64-linux-gnu/libcuda.so /usr/lib/aarch64-linux-gnu/libcuda.so.1
RUN ln -sf /usr/lib/aarch64-linux-gnu/tegra-egl/libEGL.so /usr/lib/aarch64-linux-gnu/libEGL.so
RUN ldconfig
