ARG DEPENDENCIES_IMAGE
ARG IMAGE_NAME
FROM ${DEPENDENCIES_IMAGE} as dependencies

ARG IMAGE_NAME
FROM ${IMAGE_NAME}:{{ ctx.drivers.version }}-{{ ctx.shortName }}-jetpack-{{ ctx.jetpackVersion }}-base

# CUDA libraries for L4T
{%- if ctx.drivers.version == "32.3.1" %}
RUN apt-get update && apt-get install -y --no-install-recommends cuda-libraries-10.0 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
{% else %}
ARG CUDA_TOOLKIT_PKG="cuda-repo-l4t-10-0-local-${CUDA_PKG_VERSION}_arm64.deb"

COPY --from=dependencies /data/${CUDA_TOOLKIT_PKG} ${CUDA_TOOLKIT_PKG}
RUN echo "{{ ctx.cuda['cuda-toolkit-10-0'].checksum }} ${CUDA_TOOLKIT_PKG}" | md5sum -c - && \
    dpkg --force-all -i ${CUDA_TOOLKIT_PKG} && \
    rm ${CUDA_TOOLKIT_PKG} && \
    apt-get update && apt-get install -y --no-install-recommends cuda-libraries-10.0 && \
    dpkg --purge cuda-repo-l4t-10-0-local-{{ ctx.cuda['cuda-toolkit-10-0'].version }} \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
{%- endif %}