ARG IMAGE_NAME
{%- if ctx.drivers.version != "32.3.1" and ctx.drivers.version != "32.4.3" %}
ARG DEPENDENCIES_IMAGE
FROM ${DEPENDENCIES_IMAGE} as dependencies
ARG IMAGE_NAME
{%- endif %}
FROM ${IMAGE_NAME}:{{ ctx.drivers.version }}-{{ ctx.shortName }}-jetpack-{{ ctx.jetpackVersion }}-base

# CUDA libraries for L4T

{%- if ctx.drivers.version == "32.3.1" %}
RUN apt-get update && apt-get install -y --no-install-recommends cuda-libraries-10.0 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
{%- elif ctx.drivers.version == "32.4.3" %}
RUN apt-get update && apt-get install -y --no-install-recommends cuda-libraries-10.2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
{%- else %}
COPY --from=dependencies /data/{{ ctx.cuda.toolkit.fileName }} {{ ctx.cuda.toolkit.fileName }}
RUN echo "{{ ctx.cuda.toolkit.checksum }} {{ ctx.cuda.toolkit.fileName }}" | md5sum -c - && \
    dpkg --force-all -i {{ ctx.cuda.toolkit.fileName }} && \
    rm {{ ctx.cuda.toolkit.fileName }} && \
    apt-get update && apt-get install -y --no-install-recommends cuda-libraries-10.0 && \
    dpkg --purge cuda-repo-l4t-10-0-local-{{ ctx.cuda.toolkit.version }} && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
{%- endif %}
