{%- if ctx.drivers.version == "32.4.3" -%}
ARG IMAGE_NAME
FROM ${IMAGE_NAME}:{{ ctx.drivers.version }}-{{ ctx.shortName }}-jetpack-{{ ctx.jetpackVersion }}-devel

# NVIDIA CUDA Deep Neural Network library (cuDNN)

ENV CUDNN_VERSION {{ ctx.cudnn.libcudnn8.version }}

LABEL com.nvidia.cudnn.version="{{ ctx.cudnn.libcudnn8.version }}"

RUN apt-get update && \
    apt-get install -y --no-install-recommends {{ ctx.cudnn.libcudnn8.packageName }} {{ ctx.cudnn["libcudnn8-dev"].packageName }} {{ ctx.cudnn["libcudnn8-doc"].packageName }} && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
{%- elif ctx.drivers.version == "32.3.1" -%}
ARG IMAGE_NAME
FROM ${IMAGE_NAME}:{{ ctx.drivers.version }}-{{ ctx.shortName }}-jetpack-{{ ctx.jetpackVersion }}-devel

# NVIDIA CUDA Deep Neural Network library (cuDNN)

ENV CUDNN_VERSION {{ ctx.cudnn.libcudnn7.version }}

LABEL com.nvidia.cudnn.version="{{ ctx.cudnn.libcudnn7.version }}"

RUN apt-get update && \
    apt-get install -y --no-install-recommends {{ ctx.cudnn.libcudnn7.packageName }} {{ ctx.cudnn["libcudnn7-dev"].packageName }} {{ ctx.cudnn["libcudnn7-doc"].packageName }} && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
{%- else %}
ARG DEPENDENCIES_IMAGE
ARG IMAGE_NAME
FROM ${DEPENDENCIES_IMAGE} as dependencies

ARG IMAGE_NAME
FROM ${IMAGE_NAME}:{{ ctx.drivers.version }}-{{ ctx.shortName }}-jetpack-{{ ctx.jetpackVersion }}-devel

# NVIDIA CUDA Deep Neural Network library (cuDNN)

ENV CUDNN_VERSION {{ ctx.cudnn.libcudnn7.version }}

LABEL com.nvidia.cudnn.version="${CUDNN_VERSION}"

COPY --from=dependencies /data/{{ ctx.cudnn.libcudnn7.fileName }} {{ ctx.cudnn.libcudnn7.fileName }}
RUN echo "{{ ctx.cudnn.libcudnn7.checksum }} {{ ctx.cudnn.libcudnn7.fileName }}" | md5sum -c - && \
    apt-get update && apt-get install -y --no-install-recommends /{{ ctx.cudnn.libcudnn7.fileName }} && \
    rm {{ ctx.cudnn.libcudnn7.fileName }}

COPY --from=dependencies /data/{{ ctx.cudnn['libcudnn7-dev'].fileName }} {{ ctx.cudnn['libcudnn7-dev'].fileName }}
RUN echo "{{ ctx.cudnn['libcudnn7-dev'].checksum }} {{ ctx.cudnn['libcudnn7-dev'].fileName }}" | md5sum -c - && \
    apt-get update && apt-get install -y --no-install-recommends /{{ ctx.cudnn['libcudnn7-dev'].fileName }} && \
    rm {{ ctx.cudnn['libcudnn7-dev'].fileName }}

COPY --from=dependencies /data/{{ ctx.cudnn['libcudnn7-doc'].fileName }} {{ ctx.cudnn['libcudnn7-doc'].fileName }}
RUN echo "{{ ctx.cudnn['libcudnn7-doc'].checksum }} {{ ctx.cudnn['libcudnn7-doc'].fileName }}" | md5sum -c - && \
    apt-get update && apt-get install -y --no-install-recommends /{{ ctx.cudnn['libcudnn7-doc'].fileName }} && \
    rm {{ ctx.cudnn['libcudnn7-doc'].fileName }}
{%- endif %}
